/**
 * Acciones auditables del sistema. Las de USER_ se usan desde la Fase 1,
 * Bloque B; LOGIN_SUCCESS y LOGIN_FAILED desde el Bloque C. Las de
 * CATEGORY_ y UNIT_ se usan desde la Fase 2, Bloque B; las de PRODUCT_
 * desde el Bloque C; las de PRODUCT_IMAGE_ y PRODUCT_PRIMARY_IMAGE_CHANGED
 * desde el Bloque D. Las de INVENTORY_ se usan desde la Fase 3, Bloque B,
 * resueltas internamente por StockMovementEngine (nunca por el DTO/
 * controller): no existen acciones para SALE/SALE_CANCELLATION/PURCHASE/
 * RETURN/REVERSAL porque esos orígenes/movimientos no se emiten en esta fase.
 * Las de CUSTOMER_ se usan desde la Fase 4, Bloque B; el cliente genérico
 * "Público general" nunca las genera (todos los métodos de mutación lo
 * rechazan con 409). Las de QUOTE_ se usan desde la Fase 5, Bloque B:
 * QUOTE_CREATED/UPDATED/ACCEPTED/REJECTED. No existen QUOTE_EXPIRED (el
 * vencimiento es un estado efectivo derivado, nunca persistido/escrito por
 * ningún método de esta fase) ni QUOTE_CONVERTED (la conversión real es de
 * la Fase 6; no hay evento que la produzca todavía).
 */
export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_UNBLOCKED = 'USER_UNBLOCKED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  CATEGORY_CREATED = 'CATEGORY_CREATED',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  CATEGORY_ACTIVATED = 'CATEGORY_ACTIVATED',
  CATEGORY_DEACTIVATED = 'CATEGORY_DEACTIVATED',
  UNIT_CREATED = 'UNIT_CREATED',
  UNIT_UPDATED = 'UNIT_UPDATED',
  UNIT_ACTIVATED = 'UNIT_ACTIVATED',
  UNIT_DEACTIVATED = 'UNIT_DEACTIVATED',
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_PRICE_CHANGED = 'PRODUCT_PRICE_CHANGED',
  PRODUCT_ACTIVATED = 'PRODUCT_ACTIVATED',
  PRODUCT_DEACTIVATED = 'PRODUCT_DEACTIVATED',
  PRODUCT_SPECIFICATION_CHANGED = 'PRODUCT_SPECIFICATION_CHANGED',
  PRODUCT_IMAGE_ADDED = 'PRODUCT_IMAGE_ADDED',
  PRODUCT_IMAGE_REMOVED = 'PRODUCT_IMAGE_REMOVED',
  PRODUCT_PRIMARY_IMAGE_CHANGED = 'PRODUCT_PRIMARY_IMAGE_CHANGED',
  INVENTORY_INITIAL_BALANCE_CREATED = 'INVENTORY_INITIAL_BALANCE_CREATED',
  INVENTORY_ENTRY_CREATED = 'INVENTORY_ENTRY_CREATED',
  INVENTORY_EXIT_CREATED = 'INVENTORY_EXIT_CREATED',
  INVENTORY_ADJUSTMENT_IN_CREATED = 'INVENTORY_ADJUSTMENT_IN_CREATED',
  INVENTORY_ADJUSTMENT_OUT_CREATED = 'INVENTORY_ADJUSTMENT_OUT_CREATED',
  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
  CUSTOMER_ACTIVATED = 'CUSTOMER_ACTIVATED',
  CUSTOMER_DEACTIVATED = 'CUSTOMER_DEACTIVATED',
  CUSTOMER_BLOCKED = 'CUSTOMER_BLOCKED',
  CUSTOMER_UNBLOCKED = 'CUSTOMER_UNBLOCKED',
  CUSTOMER_STAGE_CHANGED = 'CUSTOMER_STAGE_CHANGED',
  QUOTE_CREATED = 'QUOTE_CREATED',
  QUOTE_UPDATED = 'QUOTE_UPDATED',
  QUOTE_ACCEPTED = 'QUOTE_ACCEPTED',
  QUOTE_REJECTED = 'QUOTE_REJECTED',
}
